document.writeln("<!-- Header Part Start -->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<header class=\'header-area\'>");
document.writeln("  <!-- header-top -->");
document.writeln("  <div class=\'header-top\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("      <div class=\'row\'>");
document.writeln("        <div class=\'col-lg-12\'>");
document.writeln("          <div class=\'header-top-item d-block d-md-flex justify-content-between align-items-center\'>");
document.writeln("              <div class=\'header-contact\'>");
document.writeln("                <ul>");
document.writeln("                 <li><a href=\'tel:+125123658\'>Call us: CS631-631-631</a></li>");
document.writeln("                 <li><a href=\'mailto:XXX\'>Email: CS631@teamwork.com</a></li>");
document.writeln("                </ul>");
document.writeln("              </div>");
document.writeln("              <div class=\'header-top-btns\'>");
document.writeln("                <ul>");
document.writeln("                  <li><a href=\'about.html\'>Click here to be our bussiness partner</a></li>");
document.writeln("                </ul>");
document.writeln("              </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("");
document.writeln("  <!-- header-main(logo&search) -->");
document.writeln("  <div class=\'main-header\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'row align-items-center\'>");
document.writeln("            <div class=\'col-lg-2 col-md-3\'>");
document.writeln("                <div class=\'logo\'>");
document.writeln("                    <a href=\'index.html\'><img src=\'./images/NFClogo.png\' height=90px alt=\'logo\'></a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-lg-10 col-md-9\'>");
document.writeln("                <div class=\'main-header-items d-none d-md-flex justify-content-end align-items-center\'>");
document.writeln("                    <form action=\'#\'>");
document.writeln("                      <div class=\'input-box\'>");
document.writeln("                          <input type=\'text\' placeholder=\'Search for product\'>");
document.writeln("                          <button><span class=\'ti-search\'></span></button>");
document.writeln("                      </div>");
document.writeln("                    </form>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("");
document.writeln("  <!-- header-menu(navi&cart&account) -->");
document.writeln("  <div class=\'header-menu\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("      <div class=\'row\'>");
document.writeln("        <div class=\'col-lg-12\'>");
document.writeln("          <div class=\'navigation\'>");
document.writeln("            <nav class=\'navbar navbar-expand-lg navbar-light \'>");
document.writeln("");
document.writeln("                <button class=\'navbar-toggler\' type=\'button\' data-toggle=\'collapse\' data-target=\'#navbarSupportedContent\' aria-controls=\'navbarSupportedContent\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("                    <span class=\'toggler-icon\'></span>");
document.writeln("                    <span class=\'toggler-icon\'></span>");
document.writeln("                    <span class=\'toggler-icon\'></span>");
document.writeln("                </button> <!-- navbar toggler -->");
document.writeln("");
document.writeln("                <div class=\'collapse navbar-collapse sub-menu-bar\' id=\'navbarSupportedContent\'>");
document.writeln("                  <ul class=\'navbar-nav mr-auto\'>");
document.writeln("                    <li class=\'nav-item active\'><a class=\'nav-link\' href=\'index.html\'>Home</a></li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                      <a class=\'nav-link\' href=\'category.html\'>Medicine</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                      <a class=\'nav-link\' href=\'category.html\'>PPE</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                      <a class=\'nav-link\' href=\'category.html\'>PETS</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                      <a class=\'nav-link\' href=\'about.html\'>About</a>");
document.writeln("                    </li>");
document.writeln("                  </ul>");
document.writeln("                </div> <!-- navbar collapse -->");
document.writeln("");
document.writeln("                <div class=\'navbar-btn d-flex\'>");
document.writeln("                  <ul>");
document.writeln("                    <li><a href=\'cart.html\'><i class=\'ti-shopping-cart-full\'></i> Cart</a></li>");
document.writeln("                    <li><a href=\'login.html\'><i class=\'ti-user\'></i>Account</a></li>");
document.writeln("                    <li><a href=\'orders.html\'><i class=\'ti-notepad\'></i>My Order</a></li>");
document.writeln("");
document.writeln("                  </ul>");
document.writeln("                </div>");
document.writeln("           </nav>");
document.writeln("        </div> <!-- navigation -->");
document.writeln("");
document.writeln("       </div>");
document.writeln("     </div>");
document.writeln("   </div>");
document.writeln("  </div>");
document.writeln("</header>");
document.writeln("<!-- Header Part End-->");
document.writeln("");
